### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by linuskar**
Made some UI improvements by mainly improving the visuals

### CODE REVIEW

**Review by Caramajau — CHANGES_REQUESTED** [review]
I can't see the tutorial text anymore, it is probably because it is constant pixel size (it has always been weird for me, but no it is not visible at all).

**Comment by linuskar** [comment]
> I can't see the tutorial text anymore, it is probably because it is constant pixel size (it has always been weird for me, but now it is not visible at all).

fixed

**Review by Figer-op — APPROVED** [review]
i commited something so it is good

**Review by Oskmey — APPROVED** [review]
LGTM

**Review by Caramajau — APPROVED** [review]

**Pull request merged**
