### PR TITLE
Sprint 2

### PR DESCRIPTION
**Pull request by linuskar**

### CODE REVIEW

**Review by Caramajau — APPROVED** [review]

**Review by HugoUnosson — COMMENTED** [review]
Should we do this before or after Ludwig merges map -> sprint2?

**Comment by linuskar** [comment]
> Should we do this before or after Ludwig merges map -> sprint2?

Did we not agree on merging everything that was leftover during the meeting to sprint 3?

**Comment by HugoUnosson** [comment]
> > Should we do this before or after Ludwig merges map -> sprint2?
> 
> Did we not agree on merging everything that was leftover during the meeting to sprint 3? Yes, before.

Yes I think so too

**Review by Figer-op — APPROVED** [review]
ser bra ut

**Pull request merged**
